### ISSUE TITLE
`ocdev application` story

### ISSUE THREAD

**Issue by containscafeine** [redhat-developer/ocdev#24]
So, right now we have `ocdev application create` which creates a new application and binds it to the current project.
We should have the following behavior as well -
`ocdev application ___`

- [x] `<name>` - sets the given application as the current application #128 
- [x] `list` - lists all the applications
- [x] `get` - gets the currently active application #23 
- [x] `delete` - deletes the given application

**Comment by kadel** [comment]
> <name> - sets the given application as the current application

I'm not sure about this, shouldn't this maybe `set <name>`?
